server:
  port: 9003
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  #替换Tomcat容器，性能更优
  undertow:
    io-threads: 8
    worker-threads: 248
    buffer-size: 1024
  jackson:
    #指定日期格式，比如yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    #指定日期格式化时区
    time-zone: GMT+8
  datasource:
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3307/memorial?useUnicode=true&&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
          username: db136s1ehvo1yn73
          password: cxz307311SJK
          type: org.apache.commons.dbcp2.BasicDataSource
          dbcp2:
            connection-init-sqls: SET NAMES utf8mb4
  redis:
    host: 182.92.205.118
    port: 6379
yhbr:
  openid:
    APPID: wxb35ad73dc44d2754 # 微信小程序ID
    SECRET: 45f075531da78d280787590f9401455b # 微信小程序秘钥
    key: XXDBZ-ANS3P-7PHDL-VDOJJ-W7UO3-ACBPZ
logging:
  config: classpath:log4j2-back.xml
# 通用 Mapper 配置
mapper:
  identity: MYSQL
  not-empty: false
swagger:
  enable: true
