server:
  port: 9003
  servlet:
    context-path: /api/greenhome
spring:
  #替换Tomcat容器，性能更优
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
  servlet:
    multipart:
      max-file-size: 50MB # 限制文件上传的大小
      max-request-size: 100MB
  #log日志打印颜色支持
  output:
    ansi:
      enabled: always
  jackson:
    #指定日期格式，比如yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    #指定日期格式化时区
    time-zone: GMT+8
  datasource:
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://zs01:3306/memorial?useUnicode=true&&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
          username: zs
          password: zhuisi5
          type: org.apache.commons.dbcp2.BasicDataSource
          dbcp2:
            connection-init-sqls: SET NAMES utf8mb4
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
# 通用 Mapper 配置
mapper:
  identity: MYSQL
  not-empty: false
yhbr:
  openid:
    ACCESSKEY: M3ZI4L50CRlfJVsB0ygqPw-3Ic79cHPCdXl52JAZ #七牛云 ACCESSKEY
    SECRETKEY: RZ94g0qHN5COrSyDP4BhumRgNI70p0CTv47EdiLB #七牛云 SECRETKEY
    BUCKETNAME: memorial-imgs # 七牛云 BUCKETNAME
    FILEDOMAIN: http://h5cdn.zhuisi5.com/ #七牛云 cdn
logging:
  config: classpath:log4j2-back.xml